name: Build Docker image

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build_flutter:
    runs-on: ubuntu-latest
    env:
      FLUTTER_SDK_VERSION: 3.3.10
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          build-args: |
            FLUTTER_SDK_VERSION=${{ env.FLUTTER_SDK_VERSION }}
          tags: ${{ env.LOCAL_BASE_IMAGE }}