name: Build Docker image

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build_flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - run: |
          if [[ ${{ runner.os }} = "macOS" ]]
          then
            arch="macos"
          elif [[ ${{ runner.os }} = "Linux" ]]
          then
            arch="linux"
          else
            arch="windows"
          fi

          hash=$(wget --quiet -O - https://storage.googleapis.com/flutter_infra_release/releases/releases_$arch.json \
                | jq -r '.current_release.stable')

          version=$(wget --quiet -O - https://storage.googleapis.com/flutter_infra_release/releases/releases_$arch.json \
          | jq -r --arg hash "$hash" '.releases[] | select (.hash | contains($hash)) | .version')

          echo "SDK_VERSION=$version" >> $GITHUB_OUTPUT
        id: flutter

      - uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          build-args: |
            FLUTTER_SDK_VERSION=${{steps.flutter.outputs.SDK_VERSION}}
          tags: ${{ env.LOCAL_BASE_IMAGE }}