name: Publish Docker image

on:
  push:
    branches: [ "main" ]

jobs:
  build_flutter:
    runs-on: ubuntu-latest
    env:
      FLUTTER_SDK_VERSION: 3.3.10
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          build-args: |
            FLUTTER_SDK_VERSION=${{ env.FLUTTER_SDK_VERSION }}
          push: true
          tags: |
            rentready/flutter:latest
            rentready/flutter:3.3.10